language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab5-mstack
  - make -j
  - cd ./bin/
  - ./test_mstack --gtest
notifications:
  email: false
